[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v -s --html=reports/reporte.html --self-contained-html
markers =
    smoke: Pruebas de flujo critico principal
    regression: Pruebas de catalogo y regresion